<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace Calculator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>calculator.CalculateRequest</code>
 */
class CalculateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>float first_number = 1;</code>
     */
    private $first_number = 0.0;
    /**
     * <code>float last_number = 2;</code>
     */
    private $last_number = 0.0;

    public function __construct() {
        \GPBMetadata\Calculator::initOnce();
        parent::__construct();
    }

    /**
     * <code>float first_number = 1;</code>
     */
    public function getFirstNumber()
    {
        return $this->first_number;
    }

    /**
     * <code>float first_number = 1;</code>
     */
    public function setFirstNumber($var)
    {
        GPBUtil::checkFloat($var);
        $this->first_number = $var;

        return $this;
    }

    /**
     * <code>float last_number = 2;</code>
     */
    public function getLastNumber()
    {
        return $this->last_number;
    }

    /**
     * <code>float last_number = 2;</code>
     */
    public function setLastNumber($var)
    {
        GPBUtil::checkFloat($var);
        $this->last_number = $var;

        return $this;
    }

}

