<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace Calculator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>calculator.CalculateResponse</code>
 */
class CalculateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>float answer = 1;</code>
     */
    private $answer = 0.0;

    public function __construct() {
        \GPBMetadata\Calculator::initOnce();
        parent::__construct();
    }

    /**
     * <code>float answer = 1;</code>
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    /**
     * <code>float answer = 1;</code>
     */
    public function setAnswer($var)
    {
        GPBUtil::checkFloat($var);
        $this->answer = $var;

        return $this;
    }

}

